version: '2'

services:
  jenkins:
    build: 
      context: master
    volumes:
      - ./master/home:/var/jenkins_home
    ports:
      - 8080:8080
  slave1:
    build:
      context: slave1
  slave2:
    build:
      context: slave2
